### ISSUE TITLE
include typings in package.json 

### ISSUE THREAD

**Issue by xmlking** [Mitranim/ng-decorate#6]
please include `typings` (for  TypeScript  > 1.6.x) and `typescript->definition` ( as defined [here](https://github.com/DefinitelyTyped/tsd#link-to-bundled-definitions) ) in package.json 

```
  "typings": "ng-decorate/ng-decorate.d.ts",
  "typescript": {
    "definition": "ng-decorate/ng-decorate.d.ts"
  }
```

**Comment by mitranim** [comment]
Hi there! From what you said, it seems I'm missing some knowledge about `tsd`. Does it parse these properties to fetch the library's type definitions? The `tsd` readme doesn't seem to mention them.

**Comment by j-walker23** [comment]
Hey, thanks for this lib. So cool.

I was confused about the package.json stuff as well, i think this is what is means.

Running `tsd link` will download type definitions if the package.json has a key `typescript`. Like in the object above. I have not seen it being used, but that is what i gathered from it.

Either way having the definition published would be awesome! Thanks again.

**Comment by xmlking** [comment]
This one came up in the typescript 1.6 . See in the [release](http://blogs.msdn.com/b/typescript/archive/2015/09/16/announcing-typescript-1-6.aspx) under `Improvements to module resolution`

It actually link the xyz.d.ts from modules'  npm_modules into tsd.d.ts 

updated documentation on this : https://github.com/Microsoft/TypeScript/wiki/Typings-for-npm-packages

**Comment by mitranim** [comment]
Thanks for explaining, I was unaware of these new features.

I tried adding `"typings": "typings/ng-decorate/ng-decorate"` to `package.json` and compiling a demo app that uses `ng-decorate`. Evidently, the compiler does successfully locate the `.d.ts` file specified in the `ng-decorate` `package.json`, but for each import, it generates the following warning:

`error TS2306: File 'node_modules/ng-decorate/typings/ng-decorate/ng-decorate.d.ts' is not a module.`

This happens when using webpack or `tsc` from command line. So far, I haven't been able to figure this out, so I'm holding off from publishing this change. Would appreciate a clue.

**Comment by xmlking** [comment]
'reflect-metadata' project is using this approach:  
https://github.com/rbuckton/ReflectDecorators/blob/master/package.json

**Comment by mitranim** [comment]
While I was wrestling with the `"typings"` option, trying to make it work, the `reflect-decorators` repo you listed as an example ended up removing it from their `package.json`. Perhaps we'll do the same until the TypeScript guys sort this out. The `"typescript"` option for `tsd` seems to be working without any issues. I've pushed a change that adds it. Thanks.
